### ISSUE TITLE
Feature: Page displaying bar chart for battery cell voltages as fast as possible

### ISSUE THREAD

**Issue by langemand** [langemand/SoulEVSpy#4]

**Comment by JejuSoul** [comment]
Yes. This is the feature I would most like to see added.

A voltage heatmap as displayed by CanZE would be great.

[](http://www.mykiasoulev.com/forum/viewtopic.php?p=8887#p8887)

**Comment by langemand** [comment]
Voltage cell map adapted from CanZE in version 0.1.3-2888.
